// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOaENqUkyNa9hLCV58LzoY6S4N4OF4prk',
    appId: '1:564738222723:web:f16713fe7575269cc509b6',
    messagingSenderId: '564738222723',
    projectId: 'interview-task-ab28a',
    authDomain: 'interview-task-ab28a.firebaseapp.com',
    storageBucket: 'interview-task-ab28a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRgedn1CezHS3IwwLwD6jKT8GxfvEnW9Q',
    appId: '1:564738222723:android:a4c5d2e474237d55c509b6',
    messagingSenderId: '564738222723',
    projectId: 'interview-task-ab28a',
    storageBucket: 'interview-task-ab28a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7BYoSB6xT6_q7Mrw1TDJ4hHS7BP3P6Ic',
    appId: '1:564738222723:ios:3f777b69ed26bc8fc509b6',
    messagingSenderId: '564738222723',
    projectId: 'interview-task-ab28a',
    storageBucket: 'interview-task-ab28a.appspot.com',
    iosBundleId: 'com.example.eCommerceTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7BYoSB6xT6_q7Mrw1TDJ4hHS7BP3P6Ic',
    appId: '1:564738222723:ios:3f777b69ed26bc8fc509b6',
    messagingSenderId: '564738222723',
    projectId: 'interview-task-ab28a',
    storageBucket: 'interview-task-ab28a.appspot.com',
    iosBundleId: 'com.example.eCommerceTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOaENqUkyNa9hLCV58LzoY6S4N4OF4prk',
    appId: '1:564738222723:web:7cec3bd1d017dca0c509b6',
    messagingSenderId: '564738222723',
    projectId: 'interview-task-ab28a',
    authDomain: 'interview-task-ab28a.firebaseapp.com',
    storageBucket: 'interview-task-ab28a.appspot.com',
  );
}
